### ISSUE TITLE
Not all games in Games table

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#13]
This morning I finished LittleOwl, 3vars, 10vars in this sequence. They seem to be ok in Events table but 3vars is not displayed in Games table.

Could maybe somehow be related to the wrong SpeciesName issue when game is started?

**Comment by JakubLinhart** [comment]
I see these games finished on 9/19/2018 in raw data (http://mmai20180906115700.azurewebsites.net/api/games/all):

-  `Little Owl` at 7:37:15.869
- `3vars` at 7:44:40.891
- `10vars` at 7:55:16.813

All GMT+2.

I don't see it in csv file. Most likely related to #3.
