### ISSUE TITLE
setup for first test

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#18]
- JAKUB: change game plan (4x4); I will test; Maybe will need to switch back to 5x4 again later;
- JAKUB: datasets and game picking: one game randomly chosen among game variants: Little owl,  Sleepy UFO Owl (HS10_3vars), Drunken UFO Owl (HS10_10vars), Common UFO Owl (HS33_10vars), Lazy UFO Owl (HS33_10vars_long)
- JAKUB: join GAME REUSLTS and TOP10; at the beginning of top 10 for each species show mean number of turns; use 'number of turns' not 'game moves' in TOP10
- PAVEL: check texts + translate to Polish and Czech; JAKUB update texts

- JAKUB: use thumbs??? (no need to do it now, I like the current look); use JPGs thumbs as unmatched cards and Match thumb as matched cards... Each game variant has own unmatched thumb but matched thumb is same for all of them. Display numbers of pairs at the end of game. Add thumbs to game results.

**Comment by JakubLinhart** [comment]
First presentation done, closing.
