### ISSUE TITLE
report number of turns not number of cards played

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#25]
number of turns is currently the number of cards, but when you play each turn consists of playing two cards. it makes more sense to me to divide current values by two to report number of turns.

**Comment by JakubLinhart** [comment]
This requires erasing all current data to avoid semantics confusion. Is it acceptable?

**Comment by pygmy83** [comment]
ok, no problem. lets forget this

**Comment by JakubLinhart** [comment]
Add a new column: `TurnsCount`, no data erased. `TurnsCount` column is used in all statistics if available. If not available (for older games) `MovesCount / 2` is used. There are values for both columns in raw data.
