### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by JakubLinhart** [JakubLinhart/Mmai#30]
@pygmy83 translate Polish text in attached xml file and send it back, or you can directly edit the file here: https://github.com/JakubLinhart/Mmai/edit/master/src/Mmai/Resources/SharedResource.cs.resx

![image](https://user-images.githubusercontent.com/1675735/46409355-86867700-c715-11e8-81eb-7bba8d6938ab.png)

[SharedResource.cs.zip](https://github.com/JakubLinhart/Mmai/files/2441910/SharedResource.cs.zip)

**Comment by pygmy83** [comment]
Prelozeno
