### ISSUE TITLE
Change text in 'Hra'

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#40]
EXAMPLE IN ENGLISH (with paragraph spacing):
Welcome to the acoustic memory game Match-Match Animal Individuals!

After clicking on a card you will hear a call from an individual animal. Your task is to match a pair of cards with the same acoustic signature and hence belonging to the same individual. Match individuals of Little owls and one of our four fictional owl species. [MAYBE ALL THIS INFORMATION COULD BE MOVED TO POPUP WITH CONSENT WITH RESEARCH?]

Choose your game: Little owl, Sleepy UFO Owl, Drunken UFO Owl, Common UFO owl, Lazy UFO Owl

In this game, you will hear the calls of:

Drunken UFO Owl (Bold, bigger font and center above cards)

TEXT FOR OTHER LANGUAGES:
Witaj w akustycznej grze pamięciowej Dopasuj osobniki zwierząt! 
Po kliknięciu na kartę usłyszysz głos osobnika danego gatunku zwierzęcia. Twoim zadaniem jest połączyć pary kart z podobnymi głosami należące do tego samego osobnika. Połącz osobników pójdźky i cztyrech wymyślonych gatunkow sów w razem peciu wariantach gry. 

Wybierz grę: Pójdźka, Pijana UFO sowa, Śpiąca UFO sowa, Zwyczajna UFO sowa, Leniwa UFO Sowa

W tej grze usłyszysz głosy gatunku:

Śpiąca UFO sowa (Bold, bigger font and center above cards)

Vítej v akustickém pexesu "Match-Match Animal Individuals!"
Po kliknutí na kartu uslyšíš hlas jedince daného druhu. Tvým úkolem je najít dvě karty s podobným hlasem, které patří tomu samému jedinci. Spáruj jedince u sýčka obecného a čtyř dalších vymyšlených druhů sov celkem 5 variantách hry.

Vyber hru: Sýček obecný, UFO sova opilá, UFO sova usínající, UFO sova obecná, UFO sova lenivá

V této hře uslyšíš hlasy tohoto druhu:

UFO sova lenivá (Bold, bigger font and center above cards)

**Comment by JakubLinhart** [comment]
What is the goal of centering species name and placing it above cards? It doesn't look nice:
![image](https://user-images.githubusercontent.com/1675735/52593398-27660b00-2e49-11e9-8710-936711b88545.png)

**Comment by pygmy83** [comment]
It looks good! Keep it. It belongs to game plan not to description text and it makes the game variant more apparent on first sight.

**Comment by JakubLinhart** [comment]
Then _In this game, you will hear the calls of:_ text doesn't make sense. Bold game variant seems to be apparent enough. First check new version and reconsider it please :). It might be quite complex to implement "centering" for the responsive layout (e.g. mobile vs. desktop screen size) -> moving to it's own issue.
