### ISSUE TITLE
Information that the anonymized results will be used for scientific purposes?

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#41]
When the web page opens there will be popup in a respective language that results will be used for scientific purposes and that we do not store personal data. User will need to click the last sentence to get ridof the popup and start playing game. I will provide the link to the web page later...

EN
By playing this game you give consent with using results of the game for scientific purposes. All data are anonymized and we do not store personal data or provide them to any third parties.

You can find more information (only English) about the game and data collected on the website of the project “Evolution of identity signaling in vocalisations“. 

I understand and want to play the game!

PL
Grając w tę grę, wyrażasz zgodę na użycie wyników gry do celów badań naukowych. Wszystkie dane są anonimowe, nie przechowujemy danych osobowych ani nie przekazujemy ich stronom trzecim.

Więcej informacji (tylko po angielsku) o grze i danych zbieranych znalaznesz na stronie internetowej projektu "Evolution of identity signaling in vocalisations".

Rozumiem i chcę grać w tę grę!

CZ
Hraním této hry souhlasíte s využitím výsledků pro vědecké účely. Výsledky jsou plně anonymní a žádné osobní údaje neukládáme ani nepředáváme třetím stranám.

Další informace (jen anglicky) o hře i sbíraných datech najdete na webových stránkách projektu "Evolution of identity signaling in vocalisations".

Rozumím a chci hrát!

**Comment by JakubLinhart** [comment]
Not sure if it is possible to use Google Analytics without cookie consent. Either Google analytics could be disabled or e.g. this text has to be included:

```
We use Google Analytics to collect information about visitor behaviour on our website. Google Analytics stores information about what pages you visit, how long you are on the site, how you got here and what you click on. This Analytics data is collected via a JavaScript tag in the pages of our site and is not tied to personally identifiable information.We therefore do not collect or store your personal information (e.g. your name or address) so this information cannot be used to identify who you are.

You can find out more about Google’s position on privacy as regards its analytics service at http://www.google.com/intl/en_uk/analytics/privacyoverview.html
```

**Comment by pygmy83** [comment]
disable Google analytics - we will se how many games were completed and how many people...

**Comment by pygmy83** [comment]
Popup is not good, sorry. Should be probably more easy solution and more effective one. Putting the info about collection of data directly into introduction text (Hra, directly under 'Vitej v akustickem pexesu...'). Delete part: 'Rozumim a chci hrat'. and add link to web page (https://evolutionofidentitysignaling.com/)

**Comment by pygmy83** [comment]
also, czech version of info uses VY while the rest of text uses TY forms of verbs. Please, change the CZ text of context into TY form.

**Comment by JakubLinhart** [comment]
Is the text and playing the game enough to get consent?

**Comment by pygmy83** [comment]
yes, text and playing is enough...
