### ISSUE TITLE
adjust links to web pages

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#42]

**Comment by pygmy83** [comment]
In Výsledky there are links to other web pages. Delete link Sýček obecný. Leave only Projekt and Ochrana sýčka.

**Comment by pygmy83** [comment]
Play:
You can find more information (only English) about the game and data collected on the website of the project "Evolution of identity signaling in vocalisations".

set the link "Evolution of identity signaling in vocalisations" to be:
https://wordpress.com/post/evolutionofidentitysignaling.com/558

**Comment by JakubLinhart** [comment]
This is an admin link, it requires authentization. Please, send public link for the post.
