### ISSUE TITLE
Center game variant name above cards

### ISSUE THREAD

**Issue by JakubLinhart** [JakubLinhart/Mmai#45]
![image](https://user-images.githubusercontent.com/1675735/52593398-27660b00-2e49-11e9-8710-936711b88545.png)

And remove "V této hře uslyšíš".

Original issue #40.

**Comment by pygmy83** [comment]
If you think it is complex, do not bother. Just make it bold... do not waste time on it it is not important...

**Comment by pygmy83** [comment]
it is not neccessary
