### ISSUE TITLE
link from MMAI to detail instructions not working

### ISSUE THREAD

**Issue by pygmy83** [JakubLinhart/Mmai#49]
Home page (https://mmai.azurewebsites.net/):
Další informace (jen anglicky) o hře i sbíraných datech najdeš na webových stránkách projektu "Evolution of identity signaling in vocalisations".

After clicking the link "Evolution of identity signaling in vocalisations", wordpress asks for signing in.

the link is pointing here:
https://wordpress.com/post/evolutionofidentitysignaling.com/558

correct link: https://evolutionofidentitysignaling.com/2019/02/20/match-match-animal-individuals-mmai-an-acoustic-memory-game/

Correct all languages.

**Comment by JakubLinhart** [comment]
Fix deployed.
