### ISSUE TITLE
Research result data set

### ISSUE THREAD

**Issue by JakubLinhart** [JakubLinhart/Mmai#6]
Similar to /api/games table but:

- group games per player and sort them chronologically, so it is obvious what games are finished/unfinished and in which order the player have played them
- show all game events as one string
- include unfinished games - it is not possible to measure total elapsed game time for unfinished games, or it has to be defined very strictly

Maybe merge it to /api/games table.

**Comment by JakubLinhart** [comment]
@pygmy83 why serialize all game events to one string? What information is important for the game event? Event kind and time since last event?

**Comment by pygmy83** [comment]
@JakubLinhart GAME SEQUENCE: I did not realize the sequence of turns is already in Event table. Add there which card is played in a single additional column into Events log, e.g. "R1C4" to each event. This will allow to reconstruct the game plan for more detail analyses of player behaviour.

**Comment by pygmy83** [comment]
@JakubLinhart UNFINISHED GAMES: it can be just number of turns or time to the last turned card
